# Generated by Django 6.0.3 on 2026-03-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#4F46E5', max_length=7)),
                ('secondary_color', models.CharField(default='#7C3AED', max_length=7)),
                ('background_color', models.CharField(default='#F8FAFC', max_length=7)),
                ('text_color', models.CharField(default='#1E293B', max_length=7)),
                ('card_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('font_family', models.CharField(choices=[('Inter', 'Inter (Modern)'), ('Roboto', 'Roboto (Clean)'), ('Poppins', 'Poppins (Friendly)'), ('Merriweather', 'Merriweather (Serif)'), ('Fira Code', 'Fira Code (Monospace)'), ('Playfair Display', 'Playfair Display (Elegant)')], default='Inter', max_length=100)),
                ('font_size_base', models.PositiveIntegerField(default=16)),
                ('last_modified_by', models.EmailField(blank=True, max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
