# Generated by Django 5.1.15 on 2026-04-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("UPDATE", "Updated Settings"),
                            ("VIEW", "Viewed Settings"),
                            ("FAILED_AUTH", "Failed Authorization"),
                        ],
                        max_length=20,
                    ),
                ),
                ("user_email", models.EmailField(max_length=254)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "changes",
                    models.JSONField(
                        default=dict, help_text="Fields changed and old/new values"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Audit Log Entry",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user_email", "-timestamp"],
                        name="main_auditl_user_em_edfa0c_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="main_auditl_action_17a227_idx",
                    ),
                ],
            },
        ),
    ]
